plugins:
  # For contract
  - name: vyper
  # For testing/simulation
  - name: foundry
  # For bots
  # TODO: Release `aws` plugin officially
  # - name: aws
  - name: alchemy

ethereum: &use-foundry
  sepolia-fork:
    default_provider: foundry
  local:
    default_provider: foundry
optimism: *use-foundry
base: *use-foundry
