plugins:
  # For contract
  - name: vyper
  # For testing/simulation
  - name: foundry

ethereum: &use-foundry
  sepolia-fork:
    default_provider: foundry
  local:
    default_provider: foundry
optimism: *use-foundry
base: *use-foundry
