ethereum: &use-foundry
  sepolia-fork:
    default_provider: foundry
  local:
    default_provider: foundry
optimism: *use-foundry
base: *use-foundry

plugins:
  - name: base
  - name: optimism
  - name: vyper
  - name: foundry
