name: Container Images
on:
  push:
    branches:
      - main
  pull_request:
  release:
    type: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log into GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Compliance
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .silverback-images/Dockerfile.compliance
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/silverbackltd/stablecoin-compliance:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and Push Redemptions
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .silverback-images/Dockerfile.redemptions
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/silverbackltd/stablecoin-redemptions:latest
          labels: ${{ steps.meta.outputs.labels }}
