name: Container Images
on:
  push:
    branches:
      - main
  pull_request:
  release:
    type: [published]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        uses: SilverbackLtd/build-action@v1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
