FROM ghcr.io/apeworx/silverback:stable
USER root
WORKDIR /app
RUN chown harambe:harambe /app
USER harambe
COPY ape-config.yaml .
RUN ape plugins install -U .
COPY minter.json ~/.ape/accounts/bot.json
COPY bots/redemptions.py /app/bot.py
