FROM ghcr.io/apeworx/silverback:stable
USER root
WORKDIR /app
RUN chown harambe:harambe /app
USER harambe
COPY ape-config.yaml .
RUN ape plugins install -U .
COPY contracts contracts
RUN ape compile
RUN mkdir -p /home/harambe/.ape/accounts
COPY minter.json /home/harambe/.ape/accounts/bot.json
COPY bots/redemptions.py /app/bot.py
