FROM ghcr.io/apeworx/silverback:latest
USER root
WORKDIR /app
RUN chown harambe:harambe /app
USER harambe
COPY .build .
COPY contracts .
COPY ape-config.yaml .
COPY requirements.txt .
COPY database.py .
RUN pip install --upgrade pip && pip install -r requirements.txt
RUN ape plugins install -U .
COPY bots/compliance.py /app/bot.py
